version: "3"
services:
  app:
    container_name: app
    image: wangenyong/sport:part1
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"